### ISSUE TITLE
NPM Pakage

### ISSUE THREAD

**Issue by shtetl** [tkonopka/chsk#1]
Hi, 

Really fantastic work with the current features of the project.  Very promising direction.

When do you plan to have this available via npm / yarn? 

Many thanks,

**Comment by tkonopka** [comment]
Thanks for taking a look. Several parts are still changing regularly, including some core pieces, and I'd like to add a few more features. A first version could go to repository possibly in a couple of weeks.

**Comment by tkonopka** [comment]
The core package v0.1.0 is now available on npm as `@chsk/core`. The add-on packages are `@chsk/annotation`, `@chsk/band`, etc.

**Comment by tkonopka** [comment]
A few versions are now available on npm.
